### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by cjhgit** [SnailDev/SnailDev.GifMaker#1]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg exited with code 1: Error reinitializing filters!
Failed to inject frame into filter network: No such file or directory
Error while processing the decoded data for stream #0:0
Conversion failed!

    at ChildProcess.<anonymous> (D:\yunser\server\node_modules\_fluent-ffmpeg@2.1.2@fluent-ffmpeg\lib\processor.js:182:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by cjhgit** [comment]
Linux可以，Windows 不能用
